create_sandbox_target("codewars" "8-kyu-convert-a-string-to-an-array")
create_sandbox_target("codewars" "8-kyu-abbreviate-a-two-word-name")
create_sandbox_target("codewars" "8-kyu-century-from-year")
create_sandbox_target("codewars" "8-kyu-beginner-series-2-clock")
create_sandbox_target("codewars" "8-kyu-a-needle-in-the-haystack")